[package]
name = "di-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
